IntellectTechCareers/Controllers/CandidateController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using IntellectTechCareers.Data_Access_Layer;
using IntellectTechCareers.Models;
using IntellectTechCareers.Utils;

namespace IntellectTechCareers.Controllers
{
    public class CandidateController : Controller
    {
        //
        // GET: /Candidate/

        public ActionResult Index()
        {
           if (!Navigator.IsUserLoggedIn(Session))
            {
                @ViewBag.Message = "Sorry! You need to login to view this page.";
                return View("Message");
                //return RedirectToAction("Login", "Account");
            }
            else if (!Navigator.UserRoleValidation(Session, "candidate"))
            {
                @ViewBag.Message = "Access Denied !   You are not allowed to visit this page.";
                return View("Message");
                //return RedirectToAction("Login", "Account");
            }

            return View();
        }

        [HttpGet]
        public ActionResult UpdateProfile()
        {
            if (!Navigator.IsUserLoggedIn(Session))
            {
                @ViewBag.Message = "Sorry! You need to login to view this page.";
                return View("Message");
                //return RedirectToAction("Login", "Account");
            }
            else if (!Navigator.UserRoleValidation(Session, "candidate"))
            {
                @ViewBag.Message = "Access Denied !   You are not allowed to visit this page.";
                return View("Message");
                //return RedirectToAction("Login", "Account");
            }

            CandidateModel candidate = new CandidateModel();

            int user_id = ((User)Session["user"]).user_id;
            candidate = CandidateDAL.GetCandidateDetails(user_id);
            candidate.experienceDetails = CandidateDAL.GetCandidateExperienceDetails(user_id);

            List<QualificationModel> qualifications = CandidateDAL.GetQualificationDetails();
            List<SelectListItem> ugQualifications = new List<SelectListItem>();
            List<SelectListItem> pgQualifications = new List<SelectListItem>();

            ugQualifications.Add(new SelectListItem { Selected = true, Text = "<-Select->", Value = "0" });
            pgQualifications.Add(new SelectListItem { Selected = true, Text = "<-Select->", Value = "0" });

            foreach (var item in qualifications)
            {
                if (candidate.ugQualifications.Contains(Convert.ToString(item.qualification_id)))
                    continue;

                if (candidate.pgQualifications.Contains(Convert.ToString(item.qualification_id)))
                    continue;

                if (item.type.Equals("UG"))
                    ugQualifications.Add(new SelectListItem { Text = item.qualification, Value = item.qualification });
                else
                    pgQualifications.Add(new SelectListItem { Text = item.qualification, Value = item.qualification });
            }

            ViewBag.ugListData = ugQualifications;
            ViewBag.pgListData = pgQualifications;
            return View(candidate);
        }

        public string UpdatePersonalInfo(CandidateModel candidate)
        {
            CandidateDAL.UpdatePersonalInfo(candidate);
            return "";
        }

        public string UpdateQualificationDetails(CandidateModel candidate)
        {
            CandidateDAL.AddEducationDetails(candidate);
            return "";
        }

        public ActionResult ViewJobDetails()
        {
            if (!Navigator.IsUserLoggedIn(Session))
            {
                @ViewBag.Message = "Sorry! You need to login to view this page.";
                return View("Message");
                //return RedirectToAction("Login", "Account");
            }
            else if (!Navigator.UserRoleValidation(Session, "candidate"))
            {
                @ViewBag.Message = "Access Denied !   You are not allowed to visit this page.";
                return View("Message");
                //return RedirectToAction("Login", "Account");
            }

            User user = (User)Session["user"];

            CandidateModel candidate = new CandidateModel();
            candidate = CandidateDAL.GetCandidateDetails(user.user_id);
            candidate.experienceDetails = CandidateDAL.GetCandidateExperienceDetails(user.user_id);

            int totalExperience = 0;
            foreach (var item in candidate.experienceDetails)
            {
                totalExperience += item.experience;
            }

            JobViewModel jobViewModel = new JobViewModel();
            jobViewModel.jobs = CandidateDAL.GetApplicableJobs(user.user_id);;
            jobViewModel.qualifications = CandidateDAL.GetQualificationsIdToName();
            jobViewModel.candidateUgQualification = candidate.ugQualifications;
            jobViewModel.candidatePgQualification = candidate.pgQualifications;
            jobViewModel.totalExperience = totalExperience;
            jobViewModel.jobsAlreadyApplied = CandidateDAL.GetNumJobsAppliedFor(user.user_id);
            jobViewModel.appliedJobs = CandidateDAL.GetAppliedJobs(user.user_id);

            return View(jobViewModel);
        }

        [HttpPost]
        public ActionResult ApplyForJob(JobViewModel model)
        {
            if (!Navigator.IsUserLoggedIn(Session))
            {
                @ViewBag.Message = "Sorry! You need to login to view this page.";
                return View("Message");
                //return RedirectToAction("Login", "Account");
            }
            else if (!Navigator.UserRoleValidation(Session, "candidate"))
            {
                @ViewBag.Message = "Access Denied !   You are not allowed to visit this page.";
                return View("Message");
                //return RedirectToAction("Login", "Account");
            }

            User user = (User)Session["user"];
            CandidateDAL.ApplyForJobs(model.selectedJobs, user.user_id);

            return View();
        }

        public ActionResult JobApplicationSuccess()
        {
            if (!Navigator.IsUserLoggedIn(Session))
            {
                @ViewBag.Message = "Sorry! You need to login to view this page.";
                return View("Message");
                //return RedirectToAction("Login", "Account");
            }
            else if (!Navigator.UserRoleValidation(Session, "candidate"))
            {
                @ViewBag.Message = "Access Denied !   You are not allowed to visit this page.";
                return View("Message");
                //return RedirectToAction("Login", "Account");
            }

            ViewBag.Message = "You have successfully applied for the selected jobs ! You can view their status in job status view !";
            return View("Message");
        }

        public string UpdateExperienceInfo(ExperienceModel expModel)
        {
            CandidateDAL.AddExperienceDetails(expModel);
            return "";
        }

        public ActionResult ViewJobStatus()
        {
            if (!Navigator.IsUserLoggedIn(Session))
            {
                @ViewBag.Message = "Sorry! You need to login to view this page.";
                return View("Message");
                //return RedirectToAction("Login", "Account");
            }
            else if (!Navigator.UserRoleValidation(Session, "candidate"))
            {
                @ViewBag.Message = "Access Denied !   You are not allowed to visit this page.";
                return View("Message");
                //return RedirectToAction("Login", "Account");
            }

            int user_id = ((User)Session["user"]).user_id;
            List<ApplicationModel> model = CandidateDAL.GetApplicationDetails(user_id);
            return View(model);
        }

        public ActionResult GetCandidateEducationDetails()
        {
            if (!Navigator.IsUserLoggedIn(Session))
            {
                @ViewBag.Message = "Sorry! You need to login to view this page.";
                return View("Message");
                //return RedirectToAction("Login", "Account");
            }
            else if (!Navigator.UserRoleValidation(Session, "candidate"))
            {
                @ViewBag.Message = "Access Denied !   You are not allowed to visit this page.";
                return View("Message");
                //return RedirectToAction("Login", "Account");
            }

            int user_id = ((User)Session["user"]).user_id;

            QualificationViewModel viewModel = new QualificationViewModel();
            viewModel.qualifications = CandidateDAL.GetCandidateEducationDetails(user_id);

            return Json(viewModel);
        }

        public ActionResult GetCandidateExperienceDetails()
        {
            if (!Navigator.IsUserLoggedIn(Session))
            {
                @ViewBag.Message = "Sorry! You need to login to view this page.";
                return View("Message");
                //return RedirectToAction("Login", "Account");
            }
            else if (!Navigator.UserRoleValidation(Session, "candidate"))
            {
                @ViewBag.Message = "Access Denied !   You are not allowed to visit this page.";
                return View("Message");
                //return RedirectToAction("Login", "Account");
            }

            int user_id = ((User)Session["user"]).user_id;

            ExperienceViewModel viewModel = new ExperienceViewModel();
            viewModel.experience = CandidateDAL.GetCandidateExperienceDetails(user_id);

            return Json(viewModel);
        }
    }
}

IntellectTechCareers/Controllers/HomeController.cs
using IntellectTechCareers.Utils;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using IntellectTechCareers.Models;
using IntellectTechCareers.Data_Access_Layer;

namespace IntellectTechCareers.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            if (!Navigator.IsUserLoggedIn(Session))
                return RedirectToAction("Login", "Account");

            if (Session["user"] != null)
            {
                String role = ((User)Session["user"]).role ;
                
                if (role.Equals("candidate"))
                    return View("CandidateHome");
                else if (role.Equals("manager"))
                    return View("ManagerHome", AdminDAL.getManagerHome());
                else if (role.Equals("staff"))
                    return View("StaffHome", StaffDAL.GetStaffHome((User)Session["user"]));
                else if (role.Equals("interviewer"))
                    return RedirectToAction("ReleaseResults","Interviewer");
                else
                    return View();
            }
            else
                return RedirectToAction("Login", "Account");
        }

        public ActionResult About()
        {
            ViewBag.Layout = "";
            User user = ((User)Session["user"]);
            if (user != null)
            {
                if (user.role.Equals("candidate"))
                    ViewBag.Layout = "~/Views/Shared/_LayoutPageCandidate.cshtml";
                else if (user.role.Equals("manager"))
                    ViewBag.Layout = "~/Views/Shared/_LayoutPageManager.cshtml";
                else if (user.role.Equals("staff"))
                    ViewBag.Layout = "~/Views/Shared/_LayoutPageStaff.cshtml";
            }

            ViewBag.Message = "ABOUT US.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Layout = "";
            User user = ((User)Session["user"]);
            if (user != null)
            {
                if (user.role.Equals("candidate"))
                    ViewBag.Layout = "~/Views/Shared/_LayoutPageCandidate.cshtml";
                else if (user.role.Equals("manager"))
                    ViewBag.Layout = "~/Views/Shared/_LayoutPageManager.cshtml";
                else if (user.role.Equals("staff"))
                    ViewBag.Layout = "~/Views/Shared/_LayoutPageStaff.cshtml";
            }

            ViewBag.Message = "CONTACT US";

            return View();
        }

        public ActionResult Error()
        {
            return View();
        }

    }
}

IntellectTechCareers/Views/Home/About.cshtml
@{
    ViewBag.Title = "About Us";

    if (ViewBag.Layout.Equals(""))
    {
        Layout = "~/Views/Shared/_Layout.cshtml";
    }
    else
    {
        Layout = ViewBag.Layout;
    }
}

<div class="container-wrapper">
<div class="information-section">
<h2 class="information-title">About Us</h2>
<p class="information-text">Welcome to Intellect Tech, the world's largest professional network with 300 million members in over 200 countries and territories around the globe.</p>
</div>
<div class="information-section">
<h2 class="information-title">Mission</h2>
<p class="information-text">Our mission is simple: connect the world's professionals to make them more productive and successful. When you join Intellect Tech, you get access to people, jobs, news, updates, and insights that help you be great at what you do.</p>
</div>
<div class="information-section">
<h2 class="information-title">Company Info</h2>
<div class="information-text">
<p>Intellect started out in the VISA office of co-founder Kaushik and Ashish in 2015, and it officially launched on Sept 1, 2015.</p>
<p>The company's management team is made up of seasoned executives from companies like Yahoo!, Google, Microsoft, TiVo, PayPal, and Electronic Arts.</p>
<p>Intellect Tech is publicly held and has a diversified business model with revenues coming from member subscriptions, advertising sales, and talent solutions.</p>
</div>
</div>
</div>

IntellectTechCareers/Views/Home/CandidateHome.cshtml

@{
    ViewBag.Title = "Candidate Home";
    IntellectTechCareers.Models.User user = (IntellectTechCareers.Models.User)Session["user"];
    Layout = "~/Views/Shared/_LayoutPageCandidate.cshtml";
    IntellectTechCareers.Models.JobModel job = IntellectTechCareers.Data_Access_Layer.CandidateDAL.getJobForWhichUserIsSelected(user.user_id);
}

<h2>Candidate Dashboard</h2>

<h3>Welcome, @user.name </h3>
<br />

@{
    if(user.state.Equals("Selected"))
    {
        <h3><font color="green"> Congratulations ..! You have been selected for following job .. ! </font></h3>
        <b>Job ID : </b> @job.JobId

        <br />

        <b>Job Description : </b> @job.JobDesc
        
        <div>
            Please sign the below declaration and complete the process<br />
            Once you do this : <br />
            <ul>
                <li>You will be logged out</li>
                <li>Your account will be permanently deleted</li>
                <li>Our HR personnel will get in touch with your within 10 days</li>
            </ul>

            <div style="border:3px solid black;padding-left:20px;width:50%" >
                <div style="align-content:center;" >
                    <center><h3>Declaration</h3></center>
                </div>
                
                I agree that I will continue for the selected job and my account can be deleted forever.

                <center>
                    <div style="align-content:center;">
                        @using (Html.BeginForm("DeleteCandidate","Account", FormMethod.Get)) {
                            <input type="submit" value="I Accept" />
                        }
                    </div>
                </center>            
            
            </div>
            
        </div>
    }
    else
    {
        <table>
            <tr>
                <td><h3>Account status</h3></td>
                <td><h3>:</h3></td>
                @{
                    if(@user.state.Equals("Active"))
                    {
                        <td><h3><font color="green">@user.state </font></h3></td>
                    }
                    else
                    {

                        if (@user.AccountActiveDate < DateTime.Now)
                        {
                            IntellectTechCareers.Data_Access_Layer.CandidateDAL.ActivateUser(@user.user_id);
                            <td><h3><font color="green">@user.state </font></h3></td>                        
                        }
                        else
                        {
                            
                            <td><font color="red">@user.state </font></td>

                            <tr>
                                <td><h3>Your account will be unblocked on</h3></td>
                                <td><h3>:</h3></td>
                                <td><h3>@user.AccountActiveDate</h3></td>
                            </tr>
                        }
                    }                
                }
            </tr>
            <tr>
                <td><h3>View Job applications</h3></td>
                <td><h3>:</h3></td>
                <td>
                    <h3>
                    @using (Html.BeginForm("ViewJobStatus", "Candidate", FormMethod.Get))
                    {
                        @Html.AntiForgeryToken()

                        <input type="submit" value="View Job applications" />
                    }
                    </h3>
                </td>
            </tr>

            <tr>
                <td><h3>Update your profile</h3></td>
                <td><h3>:</h3></td>
                <td>
                    <h3>
                    @using (Html.BeginForm("UpdateProfile", "Candidate", FormMethod.Get)) {
                        @Html.AntiForgeryToken()
                        <input type="submit" value="Update Profile" />
                    }
                    </h3>
                </td>
            </tr>
        </table>
    }
    
}







IntellectTechCareers/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact Us";
    
    if(ViewBag.Layout.Equals(""))
    {
        Layout = "~/Views/Shared/_Layout.cshtml";
    }
    else
    {
        Layout = ViewBag.Layout;
    }
    
}

<section class="contact">
    <header>
        <h3>Phone</h3>
    </header>
    <p>
        <span class="label">Main:</span>
        <span>1900-1400-1200</span>
    </p>
    <p>
        <span class="label">After Hours:</span>
        <span>1900-1400-2400</span>
    </p>
</section>

<section class="contact">
    <header>
        <h3>Email</h3>
    </header>
    <p>
        <span class="label">Support:</span>
        <span>Support@intellecttech.com</span>
    </p>
    <p>
        <span class="label">Marketing:</span>
        <span>Marketing@intellecttech.com</span>
    </p>
    <p>
        <span class="label">General:</span>
        <span>General@intellecttech.com</span>
    </p>
</section>

<section class="contact">
    <header>
        <h3>Address</h3>
    </header>
    <p>
        VCSSI, Bagmane world technology center<br />
        KR Puram-Marathalli outer ring road  <br />
        Mahadevpura, Bangalore, India.
    </p>
</section>

IntellectTechCareers/Views/Home/Index.cshtml
@model IntellectTechCareers.Models.LoginModel
@{
    ViewBag.Title = "Home";
}
@section featured {
   @* <section class="featured">
        <div class="content-wrapper">
            <hgroup class="title">
                <h1>@ViewBag.Title.</h1>
                <h2>@ViewBag.Message</h2>
            </hgroup>
            <p>
                
            </p>
        </div>
    </section>
   *@
}
<section id="homeFeaturedContent">
<h2>Join us and make amazing things happen</h2>
<ol class="round">
    <li class="one">
        I am proud of the great quality devices we build and the cutting edge hardware innovations we are making. 
        It is amazing to see the products you worked on in the hands of millions of people. 
        <a href="http://go.microsoft.com/fwlink/?LinkId=245151">Learn more…</a>
        <h5 style="text-align:right">— Fenghua S.</h5>
        
    </li>
    <li class="two">
        I have both the possibility to work closely with a team, as well as the opportunity to work on, and have an input into the formulation of new policy.
        <a href="http://go.microsoft.com/fwlink/?LinkId=245153">Learn more…</a>
        <h5 style="text-align:right">— Sinead O'Hara</h5>
    </li>

</ol>
    </section>
<section id="homeLoginForm">
<h2>Log In. Get Hired.</h2>
@using (Html.BeginForm(new { ReturnUrl = ViewBag.ReturnUrl })) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Log in Form</legend>
        <ol>
            <li>
                @Html.LabelFor(m => m.UserName)
                @Html.TextBoxFor(m => m.UserName)
                @Html.ValidationMessageFor(m => m.UserName)
            </li>
            <li>
                @Html.LabelFor(m => m.Password)
                @Html.PasswordFor(m => m.Password)
                @Html.ValidationMessageFor(m => m.Password)
            </li>
            <li>
                @Html.CheckBoxFor(m => m.RememberMe)
                @Html.LabelFor(m => m.RememberMe, new { @class = "checkbox" })
            </li>
        </ol>
        <input type="submit" value="Log in" />
    </fieldset>
    <p>
        @Html.ActionLink("Register", "Register") if you don't have an account.
    </p>
}
    </section>

IntellectTechCareers/Views/Home/InterviewerHome.cshtml
@{
    ViewBag.Title = "InterviewerHome";
}

<h2>InterviewerHome</h2>

IntellectTechCareers/Views/Home/ManagerHome.cshtml
@model IntellectTechCareers.Models.ManagerDashBoardModel

@{
    ViewBag.Title = "Manager Home";
    Layout = "~/Views/Shared/_LayoutPageManager.cshtml";
}

@{
    String name = ((IntellectTechCareers.Models.User)Session["user"]).name;
}

<h2>Welcome Mr. @name</h2>
<br />

<fieldset>
    <legend>ManagerDashBoardModel</legend>
    <table>
        <tr>
            <td>
                <div class="display-label">
                    @Html.DisplayNameFor(model => model.TotalJobs)
                </div>
            </td>
            <td>
                <div class="display-field">
                    <b>@Html.DisplayFor(model => model.TotalJobs) </b>
                </div>
            </td>
        </tr>
        <tr>
            <td>
                <div class="display-label">
                    @Html.DisplayNameFor(model => model.TotalScheduledInterview)
                </div>
            </td>
            <td>
                <div class="display-field">
                    <b> @Html.DisplayFor(model => model.TotalScheduledInterview)</b>
                </div>
            </td>
        </tr>
        <tr>
            <td>
                <div class="display-label">
                    @Html.DisplayNameFor(model => model.TotalResults)
                </div>
            </td>
            <td>
                <div class="display-field">
                    <b> @Html.DisplayFor(model => model.TotalResults)</b>
                </div>
            </td>
        </tr>
        <tr><td><br /></td></tr>
        <tr>
            <td>
                <div class="display-label">
                    @Html.DisplayNameFor(model => model.UnscheduledInterviewJobs)
                </div>
            </td>
            <td>
                <div class="display-field">
                    <b> @Html.DisplayFor(model => model.UnscheduledInterviewJobs)</b>
                </div>
            </td>
        </tr>
        <tr>
            <td>
                <div class="display-label">
                    @Html.DisplayNameFor(model => model.ResultsNotReleased)
                </div>
            </td>
            <td>
                <div class="display-field">
                     <b>@Html.DisplayFor(model => model.ResultsNotReleased)</b>
                </div>
            </td>
        </tr>
    </table>
</fieldset>

IntellectTechCareers/Views/Home/StaffHome.cshtml
@model IntellectTechCareers.Models.StaffDashBoardModel
@{
    ViewBag.Title = "Staff Home";
    Layout = "~/Views/Shared/_LayoutPageStaff.cshtml";
}

@{
    String name = ((IntellectTechCareers.Models.User)Session["user"]).name;
}

<h2>Welcome Mr. @name</h2>
<br />

<fieldset>
    <legend>StaffDashBoardModel</legend>
    <table>
        <tr>
            <td>
                <div class="display-label">
                    @Html.DisplayNameFor(model => model.RightToPost)
                </div>
            </td>
            <td>
                <div class="display-field">
                    <b>@Html.DisplayFor(model => model.RightToPost) </b>
                </div>
            </td>
        </tr>
        <tr>
            <td>
                <div class="display-label">
                    @Html.DisplayNameFor(model => model.RightToScheduleInterview)
                </div>
            </td>
            <td>
                <div class="display-field">
                    <b> @Html.DisplayFor(model => model.RightToScheduleInterview)</b>
                </div>
            </td>
        </tr>
        <tr>
            <td>
                <div class="display-label">
                    @Html.DisplayNameFor(model => model.RightToReleaseResults)
                </div>
            </td>
            <td>
                <div class="display-field">
                    <b> @Html.DisplayFor(model => model.RightToReleaseResults)</b>
                </div>
            </td>
        </tr>
        <tr>
            <td>
                <div class="display-label">
                    @Html.DisplayNameFor(model => model.JobPosted)
                </div>
            </td>
            <td>
                <div class="display-field">
                    <b> @Html.DisplayFor(model => model.JobPosted)</b>
                </div>
            </td>
        </tr>
        <tr>
            <td>
                <div class="display-label">
                    @Html.DisplayNameFor(model => model.InterviewsScheduled)
                </div>
            </td>
            <td>
                <div class="display-field">
                     <b>@Html.DisplayFor(model => model.InterviewsScheduled)</b>
                </div>
            </td>
        </tr>
        <tr>
            <td>
                <div class="display-label">
                    @Html.DisplayNameFor(model => model.ResultsReleased)
                </div>
            </td>
            <td>
                <div class="display-field">
                     <b>@Html.DisplayFor(model => model.ResultsReleased)</b>
                </div>
            </td>
        </tr>
    </table>
</fieldset>